receivers:
  otlp:
    protocols:
      http:
      grpc:

processors:
  batch:
  groupbyattrs:
    keys:
      - app.honeycomb_api_key

exporters:
  otlp:
    endpoint: "api.honeycomb.io:443"
    auth:
      authenticator: headers_setter

extensions:
  headers_setter:
    headers:
      - action: insert
        key: x-honeycomb-team
        from_context: app.honeycomb_api_key


connectors:
  honeycomb_attribute_to_context:

service:
  extensions: [ headers_setter ]
  pipelines:
    traces/ingest:
      receivers: [otlp]
      processors: [batch, groupbyattrs]
      exporters: [honeycomb_attribute_to_context]

    traces/routed:
      receivers: [honeycomb_attribute_to_context]
      exporters: [otlp]